//
//  FilterItems.swift
//  NagBar
//
//  Created by Volen Davidov on 24.01.16.
//  Copyright © 2016 Volen Davidov. All rights reserved.
//

import Foundation

class FilterItems {
    
    typealias FIDictionary = Dictionary<String, FilterItem>

    static var storageURLOverride: URL?

    private var storageURL: URL {
        if let storageURLOverride = FilterItems.storageURLOverride {
            return storageURLOverride
        }

        let applicationSupport = NagBarStorage.applicationSupportDirectory()
        return applicationSupport
            .appendingPathComponent("com.volendavidov.NagBar", isDirectory: true)
            .appendingPathComponent("filter-items.json", isDirectory: false)
    }
    
    func getAll() -> FIDictionary {
        var filterItems: FIDictionary = [:]
        for filterItem in loadItems() {
            filterItems[FilterItems.generateKey(filterItem.host, service: filterItem.service)] = filterItem
        }
        return filterItems
    }
    
    func count() -> Int {
        return self.getAll().count
    }
    
    func getByKey(_ key: String) -> FilterItem? {
        return getAll()[key]
    }
    
    private func getKeyById(_ id: Int) -> String {
        return getAll().keys.sorted(){$0.lowercased() < $1.lowercased()}[id]
    }
    
    func getById(_ id: Int) -> FilterItem {
        let key = self.getKeyById(id)
        let result = getAll()[key]
        return result!
    }
    
    func getKeys() -> Array<String> {
        return getAll().keys.sorted()
    }
    
    func updateStatus(filterItem: FilterItem, status: Int) {
        let key = FilterItems.generateKey(filterItem.host, service: filterItem.service)
        let items = loadItems()
        if let index = items.lastIndex(where: { FilterItems.generateKey($0.host, service: $0.service) == key }) {
            items[index].status = status
        }
        filterItem.status = status
        saveItems(items)
    }
    
    func insert(key: String, value: FilterItem) {
        var items = loadItems()
        items.append(value)
        saveItems(items)
    }
    
    func removeById(_ id: Int) {
        let key = getKeyById(id)
        removeByKey(key)
    }
    
    func removeByKey(_ key: String) {
        var items = loadItems()
        let index = items.lastIndex { FilterItems.generateKey($0.host, service: $0.service) == key }!
        items.remove(at: index)
        saveItems(items)
    }

    func resetStorage() {
        try? FileManager.default.removeItem(at: storageURL)
    }

    private func loadItems() -> [FilterItem] {
        guard let data = try? Data(contentsOf: storageURL) else {
            return []
        }

        return (try? JSONDecoder().decode([FilterItem].self, from: data)) ?? []
    }

    private func saveItems(_ items: [FilterItem]) {
        do {
            let directory = storageURL.deletingLastPathComponent()
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            let data = try JSONEncoder().encode(items)
            try data.write(to: storageURL, options: .atomic)
        } catch {
            NSLog("Could not save filter items: \(error)")
        }
    }
    
    // the key for FilterItem is generated by concatenation of host and service
    class func generateKey(_ host: String, service: String) -> String {
        return host + service
    }
}
